name: owndeck
description: "A zero-cost consumer lifecycle manager."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Icons ---
  cupertino_icons: ^1.0.8

  # --- 0. Authentication (Added based on previous request) ---
  firebase_core: ^4.4.0 
  firebase_auth: ^6.1.4

  # --- 1. The Local Database (Zero Cost Storage) ---
  drift: ^2.14.0            # Powerful, type-safe SQLite wrapper
  sqlite3_flutter_libs: ^0.5.18 # The actual SQLite binaries
  path_provider: ^2.1.1     # To find where to store images on the phone
  path: ^1.8.3              # Helper for file paths

  # --- 2. The Eyes (OCR & Camera - Free On-Device) ---
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4      # To take the photo
  flutter_image_compress: ^2.1.0 # To keep app size small

  # --- 3. Notifications (Expiry Alerts) ---
  flutter_local_notifications: ^19.5.0 # Runs locally on the phone
  timezone: ^0.10.1          # Required for scheduling notifications

  # --- 4. Utilities ---
  intl: ^0.20.2             # For date formatting (e.g. "Jan 24, 2026")
  share_plus: ^12.0.1        # For the "Lost & Found" sharing
  url_launcher: ^6.2.1      # To launch email/twitter for complaints
  screenshot: ^3.0.0        # To capture the "Lost Item" card as an image
  google_sign_in: ^6.2.1
  google_fonts: ^8.0.0
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # --- Code Generation (Required for Drift) ---
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
  - assets/google.png
  - assets/only_logo.png
  - assets/full_logo.png
  - assets/side_logo.png
  

flutter_launcher_icons:
  android: true            # Overwrites the default android icon
  ios: true                # Overwrites the default iOS icon
  image_path: "assets/only_logo.png" # Points to the logo you listed in assets
  min_sdk_android: 21      # Standard android setting